import React from "react";
import type { Metadata } from "next";
import Image from "next/image";
import ExploreCategories from "./ExploreCategories";
import FeaturedProducts from "./FeaturedProducts";
import Promotions from "./Promotions";
import BestSellers from "./BestSellers";
import Tags from "./Tags";
import MobileApp from "./MobileApp";
import Benefits from "./Benefits";

export const metadata: Metadata = {
  title: "FreshBasket | Home",
  description: "Generated by create next app",
};

function Home() {
  return (
    <div>
      {/* Landing */}
      <div className="mt-[3.6rem] sm:mt-[8.6rem] bg-[url('/Assets/hero-bg.png')] bg-cover bg-center h-[23vh] md:h-[25vh] xl:h-[60vh] w-full">
        <div className="flex justify-between items-center sm:pt-0">
          <div className="pl-[1rem] md:pl-[3.5rem] sm:pl-[0.5rem] xl:pl-36 font-poppins">
            <h1 className="text-xl md:text-4xl xl:text-5xl sm:w-[60%] font-medium text-custom-black">
              Don’t miss our daily amazing deals.
            </h1>
            <p className=" text-[0.7rem] lg:text-md  text-gray-400 mt-2 sm:mt-5">
              Save up to 60% off on your first order
            </p>
            <div className="hidden sm:block">
              <input
                placeholder="Enter your email address"
                className="pl-2 h-12 w-[45%] sm: text-sm mt-10"
              />
              <button className="bg-main-green h-12  px-3.5 text-white text-sm">
                Subscribe
              </button>
            </div>
            <div>
              <button className="bg-main-green px-3.5 py-1 text-white text-xs mt-3 sm:hidden">
                Explore
              </button>
            </div>
          </div>
          <div>
            <Image
              src="/Assets/Hero-img.png"
              alt="hero"
              width={620}
              height={620}
              className="top-0 right-0 hidden sm:block"
            />
            <Image
              src="/Assets/Hero-img-mob.png"
              alt="hero"
              width={320}
              height={320}
              className="top-0 right-0 mt-3 sm:hidden"
            />
          </div>
        </div>
      </div>

      <ExploreCategories />
      <FeaturedProducts />
      <Promotions />
      <BestSellers />
      <Tags />
      <MobileApp />
      <Benefits />
    </div>
  );
}

export default Home;
{
}
